### ISSUE TITLE
Improve Jacoco report titles

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/spark-partition-sizing#34]
## Background
The report titles are all the same for each combination of Scala and Spark in the matrix. It doesn't help to differentiate between them.

## Feature
Add Scala and Spark version into the title of the Jacoco report

**Comment by miroslavpojer** [comment]
Release notes:
#34 - Improve JaCoCo report title
- Add spark and scala versions into title
- Add timestamp into title
